In [1]:
import numpy as np
from np2latex import np2latex

In [2]:
X = np.array([[1.00, 2.00, 3.14], [-1.00, 0.00, -5.12], [9.99, -2.14, 0.00]])

In [3]:
print(np2latex(X))

\left( \begin{array}{ccc} 1.00 & 2.00 & 3.14 \\ -1.00 & 0.00 & -5.12 \\ 9.99 & -2.14 & 0.00 \\ \end{array} \right)


$$\left( \begin{array}{ccc} 1.00 & 2.00 & 3.14 \\ -1.00 & 0.00 & -5.12 \\ 9.99 & -2.14 & 0.00 \\ \end{array} \right)$$

In [4]:
x = np.array([0.00, 1.23, -3.14])

In [5]:
x.reshape(-1, 1).shape

(3, 1)

In [6]:
print(np2latex(x))

\left( \begin{array}{c} 0.00 \\ 1.23 \\ -3.14 \\ \end{array} \right)


$$\left( \begin{array}{c} 0.00 \\ 1.23 \\ -3.14 \\ \end{array} \right) $$

In [7]:
print(np2latex(x, column=False))

\left( \begin{array}{ccc} 0.00 & 1.23 & -3.14 \\ \end{array} \right)


$$ \left( \begin{array}{ccc} 0.00 & 1.23 & -3.14 \\ \end{array} \right) $$